version: '3.8'

services:
  eurekaservice:
    build:
      context: .
      dockerfile: eurekaservice/Dockerfile
    container_name: eurekaservice
    ports:
      - "8761:8761"
    networks:
      - microservice-networks
  redis:
    image: redis:latest
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - microservice-networks
  apigateway:
    build:
      context: .
      dockerfile: apigateway/Dockerfile
    container_name: apigateway
    ports:
      - "8080:8080"
    networks:
      - microservice-networks
    depends_on:
      - eurekaservice
      - redis
networks:
  microservice-networks:
    driver: bridge
